version: "3.8"

services:
  mexc_ws:
    image: ghcr.io/ollebolle22/mexc-ws-influx:latest
    container_name: mexc_ws_influx
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MEXC_API_KEY=${MEXC_API_KEY}
      - MEXC_SECRET_KEY=${MEXC_SECRET_KEY}
      - MEXC_SYMBOL=${MEXC_SYMBOL}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    depends_on:
      - influxdb
    networks:
      - mexcnet

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    env_file:
      - .env
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_BUCKET=${INFLUX_BUCKET}
      - INFLUXDB_ORG=${INFLUX_ORG}
      - INFLUXDB_TOKEN=${INFLUX_TOKEN}
    networks:
      - mexcnet

networks:
  mexcnet:

volumes:
  influxdb-data:
